name: Run tests

on:
  push:
    branches-ignore: [ master, develop ]
      
  pull_request:
    types: opened
    branches: [ master, develop ]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Decrypt release secret
      run: |
        chmod +x ./.github/scripts/decrypt_key.sh
        ./.github/scripts/decrypt_key.sh
      env:
        FIREBASE_PASSPHRASE: ${{ secrets.FIREBASE_PASSPHRASE }}
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run unit tests
      run: ./gradlew test
