name: Generate test coverage report

on:
  push:
  pull_request:
    types: [opened, closed]
    branches: 
      - develop
      - master

jobs:
  coverage-report:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Decrypt release secret
      run: |
        chmod +x ./.github/scripts/decrypt_key.sh
        ./.github/scripts/decrypt_key.sh
      env:
        FIREBASE_PASSPHRASE: ${{ secrets.FIREBASE_PASSPHRASE }}
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Create coverage report
      run: ./gradlew jacocoTestReport
    
    - name: Send report to Codacy
      run: |
        export CODACY_PROJECT_TOKEN=${{secrets.CODACY_KEY}}
        bash <(curl -Ls https://coverage.codacy.com/get.sh)
